Attribute VB_Name = "modErrors"
'Consts for return codes errors
Const ERROR_NO_ERROR = 0&
Const ERROR_ALREADY_ASSIGNED = 85&
Const ERROR_ACCESS_DENIED = 5&
Const ERROR_BAD_DEVICE_TYPE = 66&
Const ERROR_BAD_NET_NAME = 67&
Const ERROR_BAD_PROFILE = 1206&
Const ERROR_BAD_DEVICE = 1200&
Const ERROR_BAD_PROVIDER = 1204&
Const ERROR_BUSY = 170&
Const ERROR_CANCEL_VIOLATION = 173&
Const ERROR_CANNOT_OPEN_PROFILE = 1205&
Const ERROR_DEVICE_ALREADY_REMEMBERED = 1202&
Const ERROR_EXTENDED_ERROR = 1208&
Const ERROR_INVALID_PASSWORD = 86&
Const ERROR_NO_NET_OR_BAD_PATH = 1203&
Const ERROR_SESSION_CREDENTIAL_CONFLICT = 1219&
Const ERROR_NO_NETWORK = 1222&
Const ERROR_CANCELLED = 1223&
Const ERROR_NO_CONNECTION = 8
Const ERROR_NO_DISCONNECT = 9
Const ERROR_DEVICE_IN_USE = 2404&
Const ERROR_NOT_CONNECTED = 2250&
Const ERROR_OPEN_FILES = 2401&
Const ERROR_MORE_DATA = 234

' New error codes from MSDN - see Q199485
Public Const HOST_NOT_FOUND = 0          'Host not found.
Public Const NO_ADDRESS = 0 = 0          '[To be supplied.]
Public Const NO_DATA = 0                 'Valid name, no data record of requested type.
Public Const NO_RECOVERY = 0             'This is a nonrecoverable error.
Public Const TRY_AGAIN = 0               'Nonauthoritative host not found.
Public Const WSABASEERR = 0              'The base value of all socket error constants. All other socket errors are offset from this value.
Public Const WSAEACCES = 10013&          'Permission denied.
Public Const WSAEADDRINUSE = 0           'Address already in use.
Public Const WSAEADDRNOTAVAIL = 0        'Cannot assign requested address.
Public Const WSAEAFNOSUPPORT = 0         'Address family not supported by protocol family.
Public Const WSAEALREADY = 0             'Operation already in progress.
Public Const WSAEBADF = 0                '[To be supplied.]
Public Const WSAECONNABORTED = 0         'Software caused connection to abort.
Public Const WSAECONNREFUSED = 0         'Connection refused.
Public Const WSAECONNRESET = 0           'Connection reset by peer.
Public Const WSAEDESTADDRREQ = 0         'Destination address required.
Public Const WSAEDISCON = 0              'Graceful shutdown in progress.
Public Const WSAEDQUOT = 0               '[To be supplied.]
Public Const WSAEFAULT = 0               'Bad address.
Public Const WSAEHOSTDOWN = 0            'Host is down.
Public Const WSAEHOSTUNREACH = 0         'No route to host.
Public Const WSAEINPROGRESS = 0          'Operation now in progress.
Public Const WSAEINTR = 0                'A blocking socket call was canceled.
Public Const WSAEINVAL = 0               'Invalid argument.
Public Const WSAEISCONN = 0              'Socket is already connected.
Public Const WSAELOOP = 0                '[To be supplied.]
Public Const WSAEMFILE = 0               'Too many open files.
Public Const WSAEMSGSIZE = 0             'Message too long.
Public Const WSAENAMETOOLONG = 0         '[To be supplied.]
Public Const WSAENETDOWN = 0             'Network is down.
Public Const WSAENETRESET = 0            'Network dropped connection on reset.
Public Const WSAENETUNREACH = 0          'Network is unreachable.
Public Const WSAENOBUFS = 0              'No buffer space available.
Public Const WSAENOPROTOOPT = 0          'Bad protocol option.
Public Const WSAENOTCONN = 0             'Socket is not connected.
Public Const WSAENOTEMPTY = 0            '[To be supplied.]
Public Const WSAENOTSOCK = 0             'Socket operation on nonsocket.
Public Const WSAEOPNOTSUPP = 0           'Operation not supported.
Public Const WSAEPFNOSUPPORT = 0         'Protocol family not supported.
Public Const WSAEPROCLIM = 0             'Too many processes.
Public Const WSAEPROTONOSUPPORT = 0      'Protocol not supported.
Public Const WSAEPROTOTYPE = 0           'Protocol wrong type for socket.
Public Const WSAEREMOTE = 0              '[To be supplied.]
Public Const WSAESHUTDOWN = 0            'Cannot send after socket shutdown.
Public Const WSAESOCKTNOSUPPORT = 0      'Socket type not supported.
Public Const WSAESTALE = 0               '[To be supplied.]
Public Const WSAETIMEDOUT = 0            'Connection timed out.
Public Const WSAETOOMANYREFS = 0         '[To be supplied.]
Public Const WSAEUSERS = 0               '[To be supplied.]
Public Const WSAEWOULDBLOCK = 0          'Resource temporarily unavailable.
Public Const WSAHOST_NOT_FOUND = 0       'Host not found.
Public Const WSANOTINITIALISED = 0       'Successful startup not yet performed.
Public Const WSANO_ADDRESS = 0           '[To be supplied.]
Public Const WSANO_DATA = 0              'Valid name, no data record of requested type.
Public Const WSANO_RECOVERY = 0          'This is a nonrecoverable error.
Public Const WSASYSNOTREADY = 0          'Network subsystem is unavailable.
Public Const WSATRY_AGAIN = 0            'Nonauthoritative host not found.
Public Const WSAVERNOTSUPPORTED = 0      'Winsock.dll out of range.
Public Const WSA_IO_PENDING = 0          'Overlapped operations will complete later.

