<style type="text/css">
    TD { font-family:tahoma; font-size:9pt; text-decoration:none;}
    BODY { font-family:tahoma; font-size:9pt; text-decoration:none;}
    A:link { color: blue; text-decoration: none }
    A:active { color: blue; text-decoration: none }
    A:visited { color: blue; text-decoration: none }
    A:hover { color: red; text-decoration: none }
    .TitleFont{	color:White; font-size:10pt; font-weight:bold; }
    .WhiteFont  { color:white; }
    .WhiteBoldFont { color : White;	font-weight : bold;	}
    .BlueFont { color:blue; }
    .SearchTitle { color: white; font-weight: bold;}
    .BlackFont	{ color:black; }
    .RedFont 	{ color:red; }
    .SmallRedFont { font:xx-small; color:red; }
    .SmallBlackFont { font:x-small; color:black; }
    .SmallestBlackFont { font:xx-small; color:black; }
    .NoteFont   { font-style: italic; color: #660000; }
    .Wingdings	 { font-family: wingdings; }
    .OrangeFont  { color:orange; }
    .GreenFont  { color:green; }
</style>