[Database]
;Path = C:\Documents\VB\SiteInfo\deploy.mdb
Path = \\tuskteam1\dos$\deploy.mdb

[Defaults]
Manufacturer=IBM
Model=633964A
Speed=1000

[PostApps]
No=1

[AppPaths]
1="c:\program files\internet explorer\iexplore.exe" http://127.0.0.1:411
