[Setup]
Domain="APAC"
Temp Dir="C:\Temp"
TestURL ="http://www.google.com"
ExecuteReefEdgePatch=False

[IPSecPatchLocations]
NT4="818043 2K.exe"
2000=""
XP=""
2003=""

[MinimumIPSec.SysVersion]
NT4=""
2000="678"
XP=""
2003=""

[ExactServicePackStringforReefEdgePatchExclusionPerOS]
NT4="AllServicePacks"
2000="Service Pack 4"
XP="Service Pack 2"
2003="Service Pack 1"