' Config.ini
' Used by SwapServer.exe to list old and new servers.

' Initial Version D. Robinson

' History
' 1.0   D. Robinson     12 Feb 2003     Initial Version - testing

' NOTE:  In this file, comments are prefixed with ' # ; or //

 # This is a comment
// This is a comment
 ' This is a comment
 ; This is a comment

' FORMAT:
' OLDSERVER, NEWSERVER

' NOTES
' \\ is not required in server names, and is removed in the SWAPSERVER.exe application.
' Server names are not case sensitive.
' Leading and trailing spaces are removed for each server name
' Anything to the right of a comment character is ignored
' A tab will be replaced with four space characters (CHR 32)

' ------------------------------------------------------------------
' OldServer, NewServer

imgsrv, tperris01