[Consolidation]
# List conditions separated by comma's.
# Each condition must have a boolean value indicating how it should be evaluated.
# Use the PIPE symbol to differentiate between conditions and text to replace with.
# ? represents a single character, * represents any number of characters
#
"The shared file*" ,"TRUE"                              | "Shared Files in Application Folder."
"The file*"        ,"TRUE","*into a directory*","FALSE" | "Shared DLL Reference Count flag not set."
"The file*"        ,"TRUE","*into a directory*","TRUE"  | "File installed into a directory other than Program Files."
"Win16 executable*","TRUE"                              | "16 bit file included in package."

[Error]
# If the description returned matches these strings, they will be classed as an Error.
#
"Invalid*"
"Upgrade*"
"The directory*"
"Component '*"
"The shortcut*"
"Class {*"
"*is a Font and must be installed*"
"*found in AdvtUISequence table. No UI is allowed*"
"*not found in Directory table*"
"*CostFinalize missing from sequence table:*"

[Warning]
# If the description returned matches these strings, they will be classed as a Warning.
#
"Reg*"
"*String"
"No*"
"Property*"
"Mismatched*"
"Complete*"
"String*"
"*defined*"
"Component:*"
"WARNING:*"
"The file '*"
"KeyPath for Component*"

[Logo]
# If the description returned matches these strings, they will classed as a Logo issue.
#
"*shared*"

[Help]
# If the selected text matches the first string, and the boolean is TRUE, the browser will be directed to the [App.Path &] URL,
# and the description pane will display the text.
# [TEXT] indicates to use the existing text.
#
"Contains*",                          "\Help\msi\over_286r.htm",[TEXT],                                                                    TRUE
"Shared DLL Reference*",              "\Help\msi\tref_09np.htm",[TEXT],                                                                    TRUE
"Shared Files in Application Folder.","\Help\msi\over_5mb2.htm","This error can be ignored.  See the help for more information.",          TRUE
"No files have been flagged*",        "",                       "This error can be ignored.",                                              FALSE
"Has an empty Key Path*",             "",                       "Further information cannot be found, but this error should be rectified.",FALSE
"16 bit file included in package.",   "",                       "This error can be ignored.",                                              FALSE
"File installed into a directory",    "",                       "This error can be ignored.",                                              FALSE
